### PR TITLE
Update version.yml

### PR DESCRIPTION
**Pull request by jsievertde**
Change in how the vaultwarden builds the docker container.

Will otherwise crash from Vaultwarden 1.30.0 onwards

### CODE REVIEW

**Comment by JensTimmerman** [comment]
@jsievertde will this not fail for everyone choosing vault warden version below 1.3.0 ?

edit: oh, it will not, this is only triggered on 'latest', when not choosing latest the given web version is used.

**Review by JensTimmerman — APPROVED** [review]

**Comment by JensTimmerman** [comment]
fixes fatal: [bitwardenqa]: FAILED! => {"changed": false, "msg": "Invalid archive '/root/.ansible/tmp/ansible-tmp-1699269613.938134-491938-264537016243341/bw_web_vonexnyu249i.tar.gz', the file is 0 bytes"}

**Comment by JensTimmerman** [comment]
@jsievertde the regex needs updating more? Doesn't work for me

**Comment by jsievertde** [comment]
Yes it seems I didn't properly validate my regex.
And yes it will fail for every release that is older than two weeks.

Hmm wouldn't it be better to track the webvault independently of vaultwarden.
And just use the latest release of the patched repo?
`https://github.com/dani-garcia/bw_web_builds`

**Comment by JensTimmerman** [comment]
@jsievertde it's ok, it won't fail, since this only triggers on latest, en latest is 1.30 or high atm.
I already fixed the regex in new pr, and released on galaxy

I don't think tracking the latest release is a good idea, I don't know why these 2 projects are released in different versions and on different cadences, but I want to keep following the official combo that is released, I think those will be tested together.

Thank you for helping me with this fix 👍

**Pull request merged**
