### PR TITLE
adding molecule test

### PR DESCRIPTION
**Pull request by chadek**
Adding molecule to test role, should close the folowing issue

https://github.com/JensTimmerman/ansible-role-vaultwarden/issues/2#issue-1038243564

### CODE REVIEW

**Comment by JensTimmerman** [comment]
Hi, Thank you for providing this boilerplate, 
The tests don't seem to be doing very much at the moment? Ideally there would be at least a check to see if the vault warden service is actually started an running at the end of the role?

**Comment by chadek** [comment]
I'm not so familiar yet with molecule, so far it helped me to test the role which does not work as is because of missing packages. I'll take a look if I can add this test. But as is, you can ensure all tasks pass and does not fail.

I'll also open an other PR to suggest a fix and install only package needed for build

**Comment by JensTimmerman** [comment]
Yeah, I agree, it can already be helpful to see if the role fails somewhere. So I'll probably merge this but not close the issue yet :)
Can you perhaps look at the listing issue and remove trailing whitespaces?

again, thank you for your contribution so far.

**Comment by JensTimmerman** [comment]
The missing packages you are talking about, are these not mentioned in the readme? If so, can you please indicate them so I can document them?

**Comment by chadek** [comment]
Previous commit should fix the lint issue. Didn't had time to checkout more tests maybe tomorrow.

**Comment by chadek** [comment]
You are right, the missing package (curl or wget) is detailed in the readme. Anyway I think it would be good to provide one of them while running the role

**Pull request merged**
